profile: full 
tap_install:
  package_repository:
    oci_repository: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages
  version:
      package_repo_bundle_tag: "1.7.0" 
      package_version: "1.7.0"

shared:
  ingress_domain: 127-0-0-1.sslip.io
  kubernetes_version: "1.27"

ceip_policy_disclosed: true
profile: iterate
supply_chain: basic

contour:
  contour:
    replicas: 1
  envoy:
    service:
      type: NodePort
    hostPorts:
      enable: true
cnrs:
  lite:
    enable: true
  pdb:
    enable: false
cartographer:
  cartographer:
    resources:
      requests:
        cpu: 100m
        memory: 200Mi

excluded_packages:
- policy.apps.tanzu.vmware.com
- image-policy-webhook.signing.apps.tanzu.vmware.com
- eventing.tanzu.vmware.com
- sso.apps.tanzu.vmware.com
